import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cibelandSidebar: [
    'intro',
    {type: 'category', label: '🐾 Productos', items: [{type: 'autogenerated', dirName: 'productos'}]},
    {type: 'category', label: '🎨 Diseño y marca', items: [{type: 'autogenerated', dirName: 'diseno'}]},
    {type: 'category', label: '🛠️ Fabricación', items: [{type: 'autogenerated', dirName: 'fabricacion'}]},
    {type: 'category', label: '🤝 Proveedores', items: [{type: 'autogenerated', dirName: 'proveedores'}]},
    {type: 'category', label: '🛒 Tienda online', items: [{type: 'autogenerated', dirName: 'tienda'}]},
    {type: 'category', label: '📣 Marketing', items: [{type: 'autogenerated', dirName: 'marketing'}]},
    {type: 'category', label: '📸 Contenido', items: [{type: 'autogenerated', dirName: 'contenido'}]},
    {type: 'category', label: '💶 Finanzas', items: [{type: 'autogenerated', dirName: 'finanzas'}]},
    {type: 'category', label: '📋 Procedimientos', items: [{type: 'autogenerated', dirName: 'procedimientos'}]},
    {type: 'category', label: '💡 Ideas', items: [{type: 'autogenerated', dirName: 'ideas'}]}
  ]
};
export default sidebars;
